name: Spectrum
version: 1.0.0
api: 3.0.0
description: Spectrum-PNX is an implementation of the Spectrum proxy for PowerNukkitX
authors: ["PowerNukkitX Team", "cooldogedev"]
main: org.powernukkitx.spectrum.Spectrum